import { Product } from '@/types';

export const products: Product[] = [
  {
    id: 1,
    name: 'The Classic Bifold',
    slug: 'classic-bifold',
    brand: 'VELLUM',
    category: 'men',
    material: 'full-grain',
    color: 'black',
    price: 3499,
    oldPrice: 4500,
    badge: 'Best Seller',
    rating: 5,
    reviews: 214,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=85',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=85',
      'https://images.unsplash.com/photo-1611010344490-5f11a1e90e17?w=800&q=85',
    ],
    description:
      'A timeless bifold crafted from premium full-grain Italian leather. Eight card slots, a deep cash compartment, and a centre ID window. Each piece develops a unique patina over time — making your wallet truly one of a kind.',
    features: [
      'Premium Italian full-grain leather',
      '8 card slots + 2 note compartments',
      'Centre ID window',
      'Hand-stitched with waxed linen thread',
      'RFID-blocking inner lining',
      'Dimensions: 11 × 9 × 1.2 cm',
    ],
    specs: {
      Material: 'Full-Grain Italian Leather',
      Lining: 'Microsuede with RFID block',
      'Card Slots': '8 + 2 bill compartments',
      Closure: 'Bifold',
      Weight: '62g',
      Dimensions: '11 × 9 × 1.2 cm',
      Origin: 'Chennai, India',
    },
    tags: ['bifold', 'classic', 'rfid', 'leather'],
  },
  {
    id: 2,
    name: 'Slim Card Carrier',
    slug: 'slim-card-carrier',
    brand: 'VELLUM',
    category: 'minimal',
    material: 'full-grain',
    color: 'tan',
    price: 1999,
    oldPrice: 2800,
    badge: 'New',
    rating: 4,
    reviews: 87,
    isNew: true,
    images: [
      'https://images.unsplash.com/photo-1612460576886-6b3dab7e64dc?w=800&q=85',
      'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=85',
    ],
    description:
      'A front-pocket card carrier engineered for the modern minimalist. Holds 4–6 cards and a few folded notes. Slips into any pocket without a bulge. Simple. Precise. Essential.',
    features: [
      'Vegetable-tanned leather',
      '4–6 card capacity',
      'Pull-tab for quick access',
      'Ultra-slim 6mm profile',
      'Natural edge finishing',
    ],
    specs: {
      Material: 'Veg-Tanned Leather',
      'Card Slots': '4–6 cards',
      Closure: 'Open top',
      Thickness: '6mm',
      Weight: '28g',
      Origin: 'Chennai, India',
    },
    tags: ['card carrier', 'minimal', 'slim', 'tan'],
  },
  {
    id: 3,
    name: 'Onyx Zip-Around',
    slug: 'onyx-zip-around',
    brand: 'VELLUM',
    category: 'men',
    material: 'genuine',
    color: 'black',
    price: 4999,
    oldPrice: 6200,
    badge: 'Premium',
    rating: 5,
    reviews: 62,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=85',
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=85',
    ],
    description:
      'Our flagship zip-around wallet. 12 card slots, a phone-sized inner pocket, and dual bill sections. Finished with champagne gold hardware. The Onyx is a statement of intention.',
    features: [
      'Buttery-soft Italian nappa leather',
      '12 card slots',
      'Phone-sized inner pocket',
      'Champagne gold hardware',
      'Full perimeter zip closure',
      'Suede lining',
    ],
    specs: {
      Material: 'Italian Nappa Leather',
      'Card Slots': '12 card + 2 bill + 1 phone',
      Closure: 'Full-zip',
      Dimensions: '19 × 9.5 cm',
      Weight: '115g',
      Origin: 'Chennai, India',
    },
    tags: ['zip', 'premium', 'flagship', 'black'],
  },
  {
    id: 4,
    name: 'Heirloom Trifold',
    slug: 'heirloom-trifold',
    brand: 'VELLUM',
    category: 'leather',
    material: 'full-grain',
    color: 'brown',
    price: 3999,
    oldPrice: 5000,
    badge: 'Heritage',
    rating: 5,
    reviews: 130,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=85',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=85',
    ],
    description:
      'A hand-burnished trifold in rich cognac brown. Built with traditional saddle-stitching, antique brass rivets, and a coin pocket. This wallet is meant to be passed down.',
    features: [
      'Hand-burnished cognac leather',
      '10 card slots + coin pocket',
      'Saddle-stitched edges',
      'Antique brass rivets',
      'Embossed VELLUM crest',
    ],
    specs: {
      Material: 'Full-Grain Cognac Leather',
      'Card Slots': '10 card + coin pocket',
      Closure: 'Trifold',
      Dimensions: '11 × 9.5 cm',
      Weight: '88g',
      Origin: 'Chennai, India',
    },
    tags: ['trifold', 'heritage', 'brown', 'leather'],
  },
  {
    id: 5,
    name: 'Blossom Chain Wallet',
    slug: 'blossom-chain-wallet',
    brand: 'VELLUM',
    category: 'women',
    material: 'genuine',
    color: 'tan',
    price: 2799,
    oldPrice: 3500,
    badge: 'New',
    rating: 4,
    reviews: 44,
    isNew: true,
    images: [
      'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&q=85',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=85',
    ],
    description:
      'A structured chain wallet in warm caramel. Detachable gold chain. Flap closure with magnetic snap. Takes you from desk to dinner without missing a beat.',
    features: [
      'Structured caramel genuine leather',
      'Detachable 60cm gold chain',
      'Magnetic flap closure',
      'Suede interior lining',
      '6 card slots + bill section',
    ],
    specs: {
      Material: 'Genuine Leather',
      'Card Slots': '6 card + 1 bill',
      Closure: 'Magnetic flap',
      Chain: 'Detachable gold-tone, 60cm',
      Weight: '130g',
      Origin: 'Chennai, India',
    },
    tags: ['chain', 'women', 'tan', 'magnetic'],
  },
  {
    id: 6,
    name: 'Velvet Zip Clutch',
    slug: 'velvet-zip-clutch',
    brand: 'FOLIO',
    category: 'women',
    material: 'synthetic',
    color: 'navy',
    price: 2199,
    oldPrice: 2900,
    rating: 4,
    reviews: 29,
    images: [
      'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&q=85',
      'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&q=85',
    ],
    description:
      'A sleek zip clutch in deep navy with brushed gold hardware. Fits phone, cards, notes, and cosmetics. A versatile companion for every occasion.',
    features: [
      'Premium vegan leather',
      'Full-zip closure',
      'Wrist strap included',
      '8 card slots + 2 zip pockets',
      'Brushed gold hardware',
    ],
    specs: {
      Material: 'Premium Vegan Leather',
      'Card Slots': '8 card + 2 zip pockets',
      Closure: 'Full-zip',
      Dimensions: '19 × 10 cm',
      Weight: '110g',
      Origin: 'Chennai, India',
    },
    tags: ['clutch', 'zip', 'navy', 'vegan'],
  },
  {
    id: 7,
    name: 'Ranger Trifold',
    slug: 'ranger-trifold',
    brand: 'FOLIO',
    category: 'leather',
    material: 'full-grain',
    color: 'tan',
    price: 3299,
    oldPrice: 4200,
    badge: 'Heritage',
    rating: 5,
    reviews: 98,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1581619009237-571b2f427b24?w=800&q=85',
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=85',
    ],
    description:
      'A tan full-grain leather trifold with contrast amber stitching. The Ranger develops a beautiful patina over years of use — a wallet with a story to tell.',
    features: [
      'Full-grain tan leather',
      'Contrast amber stitching',
      '8 card slots + coin pouch',
      'Distressed natural finish',
      'Hand-burnished edges',
    ],
    specs: {
      Material: 'Full-Grain Tan Leather',
      'Card Slots': '8 card + coin',
      Closure: 'Trifold',
      Dimensions: '11 × 9 cm',
      Weight: '82g',
      Origin: 'Chennai, India',
    },
    tags: ['trifold', 'tan', 'contrast', 'heritage'],
  },
  {
    id: 8,
    name: 'Zero Wallet',
    slug: 'zero-wallet',
    brand: 'VELLUM',
    category: 'minimal',
    material: 'genuine',
    color: 'black',
    price: 1499,
    oldPrice: 2000,
    badge: 'Minimal',
    rating: 4,
    reviews: 156,
    images: [
      'https://images.unsplash.com/photo-1606503825008-909a67e63c3d?w=800&q=85',
      'https://images.unsplash.com/photo-1612460576886-6b3dab7e64dc?w=800&q=85',
    ],
    description:
      'Ultra-thin. Zero compromise. The Zero holds 3–5 cards and a few folded notes. At just 4mm, you will forget it is there — until you need it.',
    features: [
      'Micro-slim 4mm profile',
      'Pull-through card mechanism',
      '3–5 card capacity',
      'Single-piece leather construction',
      'Laser-etched VELLUM logo',
    ],
    specs: {
      Material: 'Genuine Leather',
      'Card Slots': '3–5 cards',
      Thickness: '4mm',
      Weight: '18g',
      Origin: 'Chennai, India',
    },
    tags: ['minimal', 'slim', 'zero', 'black'],
  },
  {
    id: 9,
    name: 'The Long Flap',
    slug: 'long-flap',
    brand: 'VELLUM',
    category: 'women',
    material: 'full-grain',
    color: 'brown',
    price: 4299,
    oldPrice: 5200,
    badge: 'Premium',
    rating: 5,
    reviews: 52,
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=85',
      'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&q=85',
    ],
    description:
      'An elegant long-flap wallet in vintage brown with 12 card slots, a transparent ID window, and a coin zipper. The ultimate everyday companion for the discerning woman.',
    features: [
      'Vintage full-grain brown leather',
      '12 card slots + coin zipper',
      'Transparent ID window',
      'Snap-button flap closure',
      'Embossed floral accent',
    ],
    specs: {
      Material: 'Full-Grain Leather',
      'Card Slots': '12 card + coin',
      Closure: 'Snap flap',
      Dimensions: '19 × 9.5 cm',
      Weight: '120g',
      Origin: 'Chennai, India',
    },
    tags: ['long', 'flap', 'women', 'brown'],
  },
  {
    id: 10,
    name: 'Forest Bifold',
    slug: 'forest-bifold',
    brand: 'FOLIO',
    category: 'men',
    material: 'genuine',
    color: 'green',
    price: 2999,
    oldPrice: 3800,
    badge: 'Limited',
    rating: 4,
    reviews: 33,
    images: [
      'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=800&q=85',
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=85',
    ],
    description:
      'A bold forest-green bifold for those who reject the ordinary. Same FOLIO build quality, entirely unique character. RFID-blocking inner lining included.',
    features: [
      'Forest green genuine leather',
      '8 card slots',
      'RFID-blocking inner layer',
      'Slim 1cm profile',
      'Contrast stitching',
    ],
    specs: {
      Material: 'Genuine Leather',
      'Card Slots': '8 card + 2 bill',
      RFID: 'Blocking layer',
      Weight: '68g',
      Origin: 'Chennai, India',
    },
    tags: ['bifold', 'green', 'rfid', 'limited'],
  },
  {
    id: 11,
    name: 'Waxed Canvas Slim',
    slug: 'waxed-canvas-slim',
    brand: 'FOLIO',
    category: 'minimal',
    material: 'canvas',
    color: 'tan',
    price: 1299,
    oldPrice: 1800,
    rating: 4,
    reviews: 41,
    images: [
      'https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?w=800&q=85',
      'https://images.unsplash.com/photo-1606503825008-909a67e63c3d?w=800&q=85',
    ],
    description:
      'Waxed cotton canvas meets leather trim. A lightweight, adventure-ready wallet for explorers who travel light and live boldly.',
    features: [
      'Waxed cotton canvas body',
      'Leather accent trim',
      '4 card slots + 1 bill section',
      'YKK zip coin pocket',
      'Water-resistant finish',
    ],
    specs: {
      Material: 'Waxed Canvas + Leather',
      'Card Slots': '4 card + coin',
      Weight: '45g',
      Origin: 'Chennai, India',
    },
    tags: ['canvas', 'minimal', 'travel', 'waxed'],
  },
  {
    id: 12,
    name: 'Noir Envelope',
    slug: 'noir-envelope',
    brand: 'VELLUM',
    category: 'leather',
    material: 'full-grain',
    color: 'black',
    price: 5499,
    oldPrice: 7000,
    badge: 'Flagship',
    rating: 5,
    reviews: 18,
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=85',
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=85',
    ],
    description:
      'Our most sophisticated creation. A handmade envelope wallet in jet black with 24-karat gold-plated edges. Limited to 100 pieces annually. Each ships with a certificate of authenticity.',
    features: [
      'Jet black full-grain leather',
      '24k gold-plated edge trim',
      'Hand-burnished finish',
      'Certificate of authenticity',
      'Numbered limited edition',
      'Luxury gift box included',
    ],
    specs: {
      Material: 'Full-Grain Leather',
      Edition: 'Limited 100/year',
      Hardware: '24k gold-plated',
      Weight: '95g',
      Origin: 'Chennai, India',
    },
    tags: ['flagship', 'limited', 'envelope', 'luxury'],
  },
  {
    id: 13,
    name: 'Burgundy Passport Holder',
    slug: 'burgundy-passport',
    brand: 'VELLUM',
    category: 'travel',
    material: 'full-grain',
    color: 'burgundy',
    price: 2499,
    oldPrice: 3200,
    badge: 'Travel',
    rating: 5,
    reviews: 76,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=85',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=85',
    ],
    description:
      'A slim passport holder in deep burgundy leather. Two card slots, a boarding-pass pocket, and a pen loop. Arrive anywhere looking composed.',
    features: [
      'Deep burgundy full-grain leather',
      'Passport + boarding pass pocket',
      '2 card slots + pen loop',
      'RFID-blocking lining',
      'Stamped VELLUM interior',
    ],
    specs: {
      Material: 'Full-Grain Leather',
      Slots: 'Passport + boarding pass + 2 card',
      RFID: 'Blocking',
      Weight: '55g',
      Origin: 'Chennai, India',
    },
    tags: ['passport', 'travel', 'burgundy', 'rfid'],
  },
  {
    id: 14,
    name: 'Cognac Money Clip',
    slug: 'cognac-money-clip',
    brand: 'FOLIO',
    category: 'men',
    material: 'genuine',
    color: 'brown',
    price: 1799,
    oldPrice: 2400,
    rating: 4,
    reviews: 55,
    images: [
      'https://images.unsplash.com/photo-1611010344490-5f11a1e90e17?w=800&q=85',
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=85',
    ],
    description:
      'A sleek leather money clip in warm cognac. Stainless steel clip on one side, 2 card slots on the other. Holds up to 12 notes flat. The power move for the minimalist.',
    features: [
      'Cognac genuine leather',
      'Stainless steel money clip',
      '2 card slots',
      'Holds 12 notes flat',
      'Slim 5mm profile',
    ],
    specs: {
      Material: 'Genuine Leather + Stainless Steel',
      'Card Slots': '2 card + money clip',
      Thickness: '5mm',
      Weight: '32g',
      Origin: 'Chennai, India',
    },
    tags: ['money clip', 'minimal', 'cognac', 'men'],
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Ananya Krishnan',
    role: 'Fashion Editor, Chennai',
    text: 'The Heirloom Trifold has become my most treasured everyday carry. The leather has developed the most gorgeous patina after 8 months. Worth every rupee.',
    rating: 5,
    initials: 'AK',
    verified: true,
    product: 'Heirloom Trifold',
  },
  {
    id: 2,
    name: 'Rohan Mehta',
    role: 'Architect, Mumbai',
    text: 'Purchased the Slim Card Carrier on a whim — it is now the only wallet I will use. Perfectly minimal, exceptional leather quality. Exactly what I needed.',
    rating: 5,
    initials: 'RM',
    verified: true,
    product: 'Slim Card Carrier',
  },
  {
    id: 3,
    name: 'Deepa Iyer',
    role: 'Marketing Director',
    text: 'Bought the Blossom Chain Wallet for a wedding and received more compliments on it than my outfit. The detachable chain is such a thoughtful detail.',
    rating: 4,
    initials: 'DI',
    verified: true,
    product: 'Blossom Chain Wallet',
  },
  {
    id: 4,
    name: 'Kiran Patel',
    role: 'Entrepreneur, Bangalore',
    text: 'VELLUM does not cut corners. My Onyx Zip-Around after 2 years still looks almost new. Worth every rupee — I have bought three as gifts already.',
    rating: 5,
    initials: 'KP',
    verified: true,
    product: 'Onyx Zip-Around',
  },
  {
    id: 5,
    name: 'Priya Sundaram',
    role: 'Doctor, Coimbatore',
    text: 'Ordered the Zero Wallet after seeing it on Instagram. Arrived beautifully packaged, leather smells amazing, and it is exactly as slim as promised.',
    rating: 4,
    initials: 'PS',
    verified: true,
    product: 'Zero Wallet',
  },
  {
    id: 6,
    name: 'Arjun Nair',
    role: 'Lawyer, Delhi',
    text: 'The Classic Bifold is simply perfect. Clean lines, excellent stitching, and after 14 months of daily use there is not a single stitch out of place.',
    rating: 5,
    initials: 'AN',
    verified: true,
    product: 'Classic Bifold',
  },
];

export const BRANDS = ['VELLUM', 'FOLIO'];
export const CATEGORIES = ['men', 'women', 'leather', 'minimal', 'travel'];
export const COLORS = ['black', 'brown', 'tan', 'navy', 'green', 'burgundy'];
export const MATERIALS = ['full-grain', 'genuine', 'synthetic', 'canvas'];
export const MAX_PRICE = 8000;
